name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: A
      id: a
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: A
        setup-command: ''
        command: python 2.py
        input: ''
        expected-output: Pravda
        comparison-method: exact
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        A_RESULTS: "${{steps.a.outputs.result}}"
      with:
        runners: a
